// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "gui.h"

fltk::Choice *surface_choose=(fltk::Choice *)0;

fltk::TextDisplay *fps_display=(fltk::TextDisplay *)0;

fltk::Window* make_window() {
  fltk::Window* w;
  
  {
fltk::Window* o = new fltk::Window(540, 195);
    w = o;
    o->box(fltk::BORDER_BOX);
    o->shortcut(0xff1b);
    o->begin();
    
    {
fltk::Button* o = new fltk::Button(438, 163, 69, 23, "Zamknij");
      o->align(fltk::ALIGN_BOTTOM|fltk::ALIGN_RIGHT|fltk::ALIGN_INSIDE);
      o->tooltip("Zamknij to okno");
    }
    
    {
fltk::Choice* o = surface_choose = new fltk::Choice(130, 152, 232, 18, "Powierzchnia");
    }
    
    {
fltk::TextDisplay* o = fps_display = new fltk::TextDisplay(473, 7, 45, 28, "FPS:");
      o->box(fltk::NO_BOX);
      o->color((fltk::Color)0xb1b1b100);
    }
    
    {
fltk::Group* o = new fltk::Group(35, 9, 310, 45);
      o->begin();
      
      {
fltk::ValueSlider* o = new fltk::ValueSlider(74, 6, 215, 25);
        o->box(fltk::ENGRAVED_BOX);
      }
      new fltk::TextDisplay(35, 6, 25, 25);
      o->end();
    }
    
    {
fltk::Group* o = new fltk::Group(35, 33, 297, 47);
      o->begin();
      new fltk::ValueSlider(75, 7, 215, 25);
      new fltk::TextDisplay(35, 7, 25, 25);
      o->end();
    }
    
    {
fltk::Group* o = new fltk::Group(35, 62, 300, 43);
      o->begin();
      new fltk::ValueSlider(75, 3, 215, 25);
      new fltk::TextDisplay(35, 3, 25, 25);
      o->end();
    }
    
    {
fltk::ItemGroup* o = new fltk::ItemGroup("submenu");
      o->begin();
      new fltk::Item("item1");
      new fltk::Item("item2");
      o->end();
    }
    o->end();
    o->resizable(o);
  }
  return  w;
}
