// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef gui_h
#define gui_h
#include <fltk/Window.h>
#include <fltk/Button.h>
#include <fltk/Choice.h>
extern fltk::Choice* surface_choose;
#include <fltk/TextDisplay.h>
extern fltk::TextDisplay* fps_display;
#include <fltk/Group.h>
#include <fltk/ValueSlider.h>
#include <fltk/ItemGroup.h>
#include <fltk/Item.h>
fltk::Window* make_window();
#endif
